name: Go

on:
  issue_comment:
    types: [created]

jobs:
  re-generate:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/generate' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER')

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
          ref: ${{ steps.pr_data.outputs.branch }}
      - run: mkdir cmd || exit 0
      - run: touch cmd/fortifyExecuteScan_generated.go
      - run: git status --short
#      - name: push
#        uses: github-actions-x/commit@v2.8
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          push-branch: ${{ steps.pr_data.outputs.branch }}
#          files: cmd/*_generated.go
#          commit-message: 'chore: update generated sources'
#          name: 'github-actions[bot]'
#          email: 'github-actions[bot]@users.noreply.github.com'
      - name: git config
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: git add
        run: |
          git add cmd/*_generated.go
      - name: git commit
        run: |
          git commit -m "chore: update generated sources"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.pr_data.outputs.branch }}
